#!/bin/bash

# Oneplus 3 root tookit version 1.0

# Website: https://j2java.net
# Source: https://github.com/black-dragon74/Oneplus3_Toolkit_Linux
# Author: black.dragon74

# Variable Declarations
author=black.dragon74
scriptVersion=1.0
home=$(echo $HOME)
mName=$(uname -n)

# Functions for the program. Let's start by decalring some basic functions.
function printHeader(){
	echo -e "Oneplus 3 tookit version $scriptVersion running on $mName."
}

function printHelp(){
	printHeader
	echo usage\: toolkit [help]\|[-h] Prints help\(this\) information.
	echo \ \ \ \ \ \ \ toolkit [backup]\|[-b] Generates a backup of your Anroid.
	echo \ \ \ \ \ \ \ toolkit [restore]\|[-r] Restores created backup.
	echo \ \ \ \ \ \ \ toolkit [unlock]\|[-u] Unlock the bootloader of your device.
	echo \ \ \ \ \ \ \ toolkit [lock]\|[-l] Locks the bootloader of your device.
	echo \ \ \ \ \ \ \ toolkit [twrp]\|[-t] Flashes TWRP to your device.
	echo \ \ \ \ \ \ \ toolkit [boottwrp]\|[-bt] Hotboots TWRP without actually flashing it.
	echo \ \ \ \ \ \ \ toolkit [stock]\|[-s] Flashes stock recovery to your device.
	echo \ \ \ \ \ \ \ tookit [check]\|[-c] Check the bootloader status.
	echo \ \ \ \ \ \ \ toolkit [update]\|[-up] Update the script version.
}

function abortError(){
	echo -e "Error occoured. Aborting..."
	exit
}

function abortSuccess(){
	echo -e "Program completed successfully..."
	exit
}

function checkADB(){
	if [ -e /usr/bin/adb ];
		then
		# Consume
	else
		echo -e "ADB Not found."
		abortError
	fi
}

function checkFastboot(){
	if [ -e /usr/bin/fastboot ];
		then
		# Consume
	else
		echo -e "Fastboot not found."
		abortError
}

function checkVersion(){
	echo -e "$scriptVersion"
}

function updateScript(){
	echo -e "Checking version on the remote."
	cd $home
	curl -o scriptVersion https://raw.githubusercontent.com/black-dragon74/Oneplus3_Toolkit_Linux/master/scriptVersion &>/dev/null
	chmod 755 ./scriptVersion
	if [ $(toolkit -v) == $(cat ./scriptVersion)];
		then
		echo -e "Script is already updated."
		rm ./scriptVersion
	else
		echo -e "Updating Script..."
		echo -e "Downloading latest version."
		cd $home
		curl -o toolkit https://raw.githubusercontent.com/black-dragon74/Oneplus3_Toolkit_Linux/master/toolkit &>/dev/null
		sudo rm /usr/bin/toolkit
		chmod 755 ./toolkit
		sudo cp ./toolkit /usr/bin/
		echo -e "Script updated."
		rm ./toolkit
	fi
}